# ================ LED as OUTPUTS ======================================
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]

# ================ INPUTS =============================================
set_property PACKAGE_PIN U18 [get_ports reset_btn]
set_property IOSTANDARD LVCMOS33 [get_ports reset_btn]
#set_property PULLUP true [get_ports reset_btn]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports scl_in]
set_property PACKAGE_PIN N1 [get_ports scl_in]

set_property IOSTANDARD LVCMOS33 [get_ports sda_in]
set_property PACKAGE_PIN M1 [get_ports sda_in]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

# =============== SYSTEM CLOCK =========================================
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]


# =============== ILA DEBUGGER =========================================
set_property MARK_DEBUG true [get_nets {byte_cnt[0]}]
set_property MARK_DEBUG true [get_nets {byte_cnt[1]}]
set_property MARK_DEBUG true [get_nets {byte_cnt[2]}]
set_property MARK_DEBUG true [get_nets {byte_cnt[3]}]
set_property MARK_DEBUG true [get_nets {byte_cnt[4]}]
set_property MARK_DEBUG true [get_nets {byte_cnt[5]}]
set_property MARK_DEBUG true [get_nets {byte_cnt[6]}]
set_property MARK_DEBUG true [get_nets {byte_cnt[7]}]
set_property MARK_DEBUG true [get_nets {data_scope[0]}]
set_property MARK_DEBUG true [get_nets {data_scope[1]}]
set_property MARK_DEBUG true [get_nets {data_scope[2]}]
set_property MARK_DEBUG true [get_nets {data_scope[3]}]
set_property MARK_DEBUG true [get_nets {data_scope[4]}]
set_property MARK_DEBUG true [get_nets {data_scope[5]}]
set_property MARK_DEBUG true [get_nets {data_scope[6]}]
set_property MARK_DEBUG true [get_nets {data_scope[7]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[0]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[4]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[6]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[9]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[12]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[8]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[10]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[1]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[2]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[7]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[11]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[13]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[14]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[15]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[3]}]
set_property MARK_DEBUG true [get_nets {pack_cnt[5]}]
set_property MARK_DEBUG true [get_nets {s_address_scope[0]}]
set_property MARK_DEBUG true [get_nets {s_address_scope[1]}]
set_property MARK_DEBUG true [get_nets {s_address_scope[2]}]
set_property MARK_DEBUG true [get_nets {s_address_scope[3]}]
set_property MARK_DEBUG true [get_nets {s_address_scope[4]}]
set_property MARK_DEBUG true [get_nets {s_address_scope[5]}]
set_property MARK_DEBUG true [get_nets {s_address_scope[6]}]
set_property MARK_DEBUG true [get_nets ack_addr_scope]
set_property MARK_DEBUG true [get_nets ack_data_scope]
set_property MARK_DEBUG true [get_nets rw_scope]
set_property MARK_DEBUG true [get_nets scl_scope]
set_property MARK_DEBUG true [get_nets sda_scope]
set_property MARK_DEBUG true [get_nets trigger_flag]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {pack_cnt[0]} {pack_cnt[1]} {pack_cnt[2]} {pack_cnt[3]} {pack_cnt[4]} {pack_cnt[5]} {pack_cnt[6]} {pack_cnt[7]} {pack_cnt[8]} {pack_cnt[9]} {pack_cnt[10]} {pack_cnt[11]} {pack_cnt[12]} {pack_cnt[13]} {pack_cnt[14]} {pack_cnt[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {byte_cnt[0]} {byte_cnt[1]} {byte_cnt[2]} {byte_cnt[3]} {byte_cnt[4]} {byte_cnt[5]} {byte_cnt[6]} {byte_cnt[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 7 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {s_address_scope[0]} {s_address_scope[1]} {s_address_scope[2]} {s_address_scope[3]} {s_address_scope[4]} {s_address_scope[5]} {s_address_scope[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {data_scope[0]} {data_scope[1]} {data_scope[2]} {data_scope[3]} {data_scope[4]} {data_scope[5]} {data_scope[6]} {data_scope[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list ack_addr_scope]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list ack_data_scope]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list rw_scope]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list scl_scope]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list sda_scope]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list trigger_flag]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
